blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/LaughingLeader/BG3ModManager/discussions/new?category=q-a
    about: Ask a question under Discussions section
